#  USERS SECTION

### GET USERS

GET http://localhost:3000/api/auth/users
Content-Type: application/json

### REGISTER USER

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "name@gmail.com",
    "username": "Carl",
    "password": "789",
    "firstname": "Francesco",
    "lastname": "serauto",
    "citta": "Roma",
    "indirizzo": "via Roma 4"
}

### REGISTER ADMIN

POST http://localhost:3000/api/auth/admin/register
Content-Type: application/json

{
    "email": "adim@gmail.com",
    "username": "Admin",
    "password": "567",
    "firstname": "Admin",
    "lastname": "Admin",
    "citta": "Bologna",
    "indirizzo": "via Roma 4"
}

### LOGIN USER

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "adim@gmail.com",
    "password": "567"
}

### LOGOUT 

GET  http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJlbWFpbCI6Im5hbWVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJDYXJsIiwicGFzc3dvcmQiOiI3ODkiLCJmaXJzdG5hbWUiOiJGcmFuY2VzY28iLCJsYXN0bmFtZSI6InNlcmF1dG8iLCJjaXR0YSI6IlJvbWEiLCJpbmRpcml6em8iOiJ2aWEgUm9tYSA0IiwiYWRtaW4iOmZhbHNlfSwiaWF0IjoxNzIxOTg2NzI1LCJleHAiOjE3MjE5ODg1MjV9.CrpOQZmZ1aFK8rmR3I1G0Szd7Ep-u-YC3T7ehbWifck


### GET USERS LOGGED

GET http://localhost:3000/api/auth/user/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJlbWFpbCI6Im5hbWVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJDYXJsIiwicGFzc3dvcmQiOiI3ODkiLCJmaXJzdG5hbWUiOiJGcmFuY2VzY28iLCJsYXN0bmFtZSI6InNlcmF1dG8iLCJjaXR0YSI6IlJvbWEiLCJpbmRpcml6em8iOiJ2aWEgUm9tYSA0IiwiYWRtaW4iOmZhbHNlfSwiaWF0IjoxNzIxOTg2NzI1LCJleHAiOjE3MjE5ODg1MjV9.CrpOQZmZ1aFK8rmR3I1G0Szd7Ep-u-YC3T7ehbWifck



# |----------------------|


# PRODOCTS SECTION

### GET ALL PRODUCTS
GET http://localhost:3000/api/products
Content-Type: application/json

### GET PRODUCT BY ID

GET http://localhost:3000/api/products/3
Content-Type: application/json

### CREATE PRODUCT BY ADMIN

POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJlbWFpbCI6ImFkaW1AZ21haWwuY29tIiwidXNlcm5hbWUiOiJBZG1pbiIsInBhc3N3b3JkIjoiNTY3IiwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IkFkbWluIiwiY2l0dGEiOiJCb2xvZ25hIiwiaW5kaXJpenpvIjoidmlhIFJvbWEgNCIsImFkbWluIjp0cnVlfSwiaWF0IjoxNzIxOTg4MzkyLCJleHAiOjE3MjE5OTAxOTJ9.n2DrFNrwQAVP8QKhs81d3JbPKK21SQ7pX0bkFdR85_8


{
    "title": "iphone",
    "price": 2000,
    "category": "phone",
    "description": "bello",
    "image": "ciccio"
}

### UPDATE PRODUCT BY ADMIN

PUT http://localhost:3000/api/products/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJlbWFpbCI6ImFkaW1AZ21haWwuY29tIiwidXNlcm5hbWUiOiJBZG1pbiIsInBhc3N3b3JkIjoiNTY3IiwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IkFkbWluIiwiY2l0dGEiOiJCb2xvZ25hIiwiaW5kaXJpenpvIjoidmlhIFJvbWEgNCIsImFkbWluIjp0cnVlfSwiaWF0IjoxNzIxOTg4Nzc3LCJleHAiOjE3MjE5OTA1Nzd9.hcajpLc9q4keTDRQIFilEAec_MkzExrsmO39WQHQ6IE


{
    "title": "prodotto modificato",
    "price": 35,
    "category": "gamingggg",
    "description": "bello00",
    "image": "pippo"
}


### DELETE PRODUCT BY ADMIN
DELETE http://localhost:3000/api/products/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJlbWFpbCI6ImFkaW1AZ21haWwuY29tIiwidXNlcm5hbWUiOiJBZG1pbiIsInBhc3N3b3JkIjoiNTY3IiwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IkFkbWluIiwiY2l0dGEiOiJCb2xvZ25hIiwiaW5kaXJpenpvIjoidmlhIFJvbWEgNCIsImFkbWluIjp0cnVlfSwiaWF0IjoxNzIxOTg4Nzc3LCJleHAiOjE3MjE5OTA1Nzd9.hcajpLc9q4keTDRQIFilEAec_MkzExrsmO39WQHQ6IE

### DELETE USER

DELETE http://localhost:3000/api/auth/user/8
Content-Type: application/json
Authorization: Bearer 



# |----------------------|

# ORDERS SECTION

### CREATE ORDER
POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer

{
    "userid":"",
    "quantity":"",
    "status":"",
    "productid":""
}

### ALL USER ORDER
GET http://localhost:3000/api/orders/id
Content-Type: application/json
Authorization: Bearer

### ORDER DETAILS
GET http://localhost:3000/api/orders/orderid
Content-Type: application/json
Authorization: Bearer
















### CHANGE STATUS FROM ADMIN
PATCH http://localhost:3000/api/orders/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJlbWFpbCI6ImFkaW1AZ21haWwuY29tIiwidXNlcm5hbWUiOiJBZG1pbiIsInBhc3N3b3JkIjoiNTY3IiwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IkFkbWluIiwiY2l0dGEiOiJCb2xvZ25hIiwiaW5kaXJpenpvIjoidmlhIFJvbWEgNCIsImFkbWluIjp0cnVlfSwiaWF0IjoxNzIyMDAwMjYyLCJleHAiOjE3MjIwMDIwNjJ9.ACoE0kUV5ri-gI5Tnd8UbQ8Aep-XQKciENj-T-62acM

{
    "status":"consegnato"
}























### DELETE FROM ADMIN
DELETE http://localhost:3000/api/orders/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJlbWFpbCI6ImFkaW1AZ21haWwuY29tIiwidXNlcm5hbWUiOiJBZG1pbiIsInBhc3N3b3JkIjoiNTY3IiwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IkFkbWluIiwiY2l0dGEiOiJCb2xvZ25hIiwiaW5kaXJpenpvIjoidmlhIFJvbWEgNCIsImFkbWluIjp0cnVlfSwiaWF0IjoxNzIyMDAxMTg2LCJleHAiOjE3MjIwMDI5ODZ9.0O4duPB5Q0Xo610Z4l97WE8LypNcrW2Ph_r24E_g82Y
