#  USERS SECTION

### GET USERS

GET http://localhost:3000/api/auth/users
Content-Type: application/json

### REGISTER USER

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "name@gmail.com",
    "username": "Carl",
    "password": "789",
    "firstname": "Francesco",
    "lastname": "serauto",
    "citta": "Roma",
    "indirizzo": "via Roma 4"
}

### REGISTER ADMIN

POST http://localhost:3000/api/auth/admin/register
Content-Type: application/json

{
    "email": "adim@gmail.com",
    "username": "Admin",
    "password": "567",
    "firstname": "Admin",
    "lastname": "Admin",
    "citta": "Bologna",
    "indirizzo": "via Roma 4"
}

### LOGIN USER

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "1234"
}

### LOGOUT 

GET  http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKb2huRG9lIiwicGFzc3dvcmQiOiIxMjM0IiwiZmlyc3RuYW1lIjoiRnJhbmNlc2NvIiwibGFzdG5hbWUiOiJDb25pZ2xpbyIsImNpdHRhIjoiQm9sb2duYSIsImluZGlyaXp6byI6InZpYSBSb21hIDQifSwiaWF0IjoxNzIxOTA4MjAxLCJleHAiOjE3MjE5MTAwMDF9.INiBWrEk4XsqNLuCR31pftABRF2HxVADsBoZCvZP6M8


### GET USERS LOGGED

GET http://localhost:3000/api/auth/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKb2huRG9lIiwicGFzc3dvcmQiOiIxMjM0IiwiZmlyc3RuYW1lIjoiRnJhbmNlc2NvIiwibGFzdG5hbWUiOiJDb25pZ2xpbyIsImNpdHRhIjoiQm9sb2duYSIsImluZGlyaXp6byI6InZpYSBSb21hIDQifSwiaWF0IjoxNzIxOTA3Njg4LCJleHAiOjE3MjE5MDk0ODh9.mBR-vIFluruCBydfdb1X7Nz_XK-1bYJINPPqP-6xL28


# |----------------------|


# PRODOCTS SECTION

### GET ALL PRODUCTS
GET http://localhost:3000/api/products
Content-Type: application/json

### GET PRODUCT BY ID

GET http://localhost:3000/api/products/1
Content-Type: application/json

### CREATE PRODUCT BY ADMIN

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "title": "prodotto",
    "price": 33,
    "category": "gaming",
    "description": "bello",
    "image": "ciccio"
}

### UPDATE PRODUCT BY ADMIN

PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
    "title": "prodotto modificato",
    "price": 35,
    "category": "gamingggg",
    "description": "bello00",
    "image": "pippo"
}


### DELETE PRODUCT BY ADMIN
DELETE http://localhost:3000/api/products/1
Content-Type: application/json


